//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public int AccessControlID { get; set; }
        public int UserID { get; set; }
        public int NMVNTaskID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int AccessLevel { get; set; }
        public bool ApprovalPermitted { get; set; }
        public bool UnApprovalPermitted { get; set; }
        public bool VoidablePermitted { get; set; }
        public bool UnVoidablePermitted { get; set; }
        public Nullable<int> AccessLevelBACKUP { get; set; }
        public Nullable<bool> ApprovalPermittedBACKUP { get; set; }
        public Nullable<bool> UnApprovalPermittedBACKUP { get; set; }
        public bool ShowDiscount { get; set; }
        public bool InActive { get; set; }
    
        public virtual OrganizationalUnit OrganizationalUnit { get; set; }
    }
}
