//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class AccountInvoiceIndex
    {
        public int AccountInvoiceID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string VATInvoiceNo { get; set; }
        public string LocationCode { get; set; }
        public string Description { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalListedGrossAmount { get; set; }
        public System.DateTime VATInvoiceDate { get; set; }
        public string CustomerName { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<System.DateTime> GoodsIssueEntryDate { get; set; }
        public string GoodsIssueReferences { get; set; }
    }
}
