//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CreditNoteIndex
    {
        public int CreditNoteID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionVouchers { get; set; }
        public string MemoCode { get; set; }
        public Nullable<System.DateTime> MemoDate { get; set; }
        public string LocationCode { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public Nullable<decimal> TotalGrossAmountPending { get; set; }
        public bool Approved { get; set; }
    }
}
