//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class CustomerIndex
    {
        public int CustomerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string OfficialName { get; set; }
        public string BillingAddress { get; set; }
        public int CustomerCategoryID { get; set; }
        public string VATCode { get; set; }
        public string ShippingAddress { get; set; }
        public string PriceCategoryCode { get; set; }
        public string SalespersonName { get; set; }
        public string TerritoryName { get; set; }
        public string Category { get; set; }
    }
}
