//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntireTerritory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntireTerritory()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int TerritoryID { get; set; }
        public string Name { get; set; }
        public string EntireName { get; set; }
        public int TerritoryID1 { get; set; }
        public string Name1 { get; set; }
        public int TerritoryID2 { get; set; }
        public string Name2 { get; set; }
        public int TerritoryID3 { get; set; }
        public string Name3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
