//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class HandlingUnitPendingGoodsIssueDetail
    {
        public int GoodsIssueID { get; set; }
        public int GoodsIssueDetailID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string BillingAddress { get; set; }
        public string ReceiverCode { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<double> UnitWeight { get; set; }
        public decimal Weight { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public string GoodsIssueReference { get; set; }
        public System.DateTime GoodsIssueEntryDate { get; set; }
    }
}
