//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleID { get; set; }
        public string Description { get; set; }
        public string DescriptionEN { get; set; }
        public int SerialID { get; set; }
        public string ImageIndex { get; set; }
        public int InActive { get; set; }
    }
}
