//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PendingDeliveryAdviceDescription
    {
        public int DeliveryAdviceID { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
    }
}
