//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PromotionIndex
    {
        public int PromotionID { get; set; }
        public string Reference { get; set; }
        public int CommodityBrandID { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal ControlFreeQuantity { get; set; }
        public bool ApplyToAllCustomers { get; set; }
        public bool ApplyToAllCommodities { get; set; }
        public bool ApplyToTradeDiscount { get; set; }
        public string Remarks { get; set; }
        public bool InActive { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
