//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class ReceiptIndex
    {
        public int ReceiptID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string LocationCode { get; set; }
        public decimal TotalDepositAmount { get; set; }
        public string Description { get; set; }
        public string CustomerName { get; set; }
        public string GoodsIssueReferences { get; set; }
        public string ReceiptTypeCode { get; set; }
        public string MonetaryAccountCode { get; set; }
        public string AdvanceReceiptReference { get; set; }
        public Nullable<System.DateTime> AdvanceReceiptDate { get; set; }
        public string SalesReturnReference { get; set; }
        public Nullable<System.DateTime> SalesReturnDate { get; set; }
        public string CreditNoteReference { get; set; }
        public Nullable<System.DateTime> CreditNoteDate { get; set; }
        public decimal TotalReceiptAmount { get; set; }
        public decimal TotalCashDiscount { get; set; }
        public Nullable<decimal> TotalDepositAmountPending { get; set; }
        public int ReceiptTypeID { get; set; }
        public decimal TotalOtherDiscount { get; set; }
        public decimal TotalFluctuationAmount { get; set; }
    }
}
