//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ReceiptDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int ReceiptID { get; set; }
        public int CustomerID { get; set; }
        public int GoodsIssueID { get; set; }
        public decimal ReceiptAmount { get; set; }
        public decimal CashDiscount { get; set; }
        public decimal FluctuationAmount { get; set; }
        public string Remarks { get; set; }
        public decimal OtherDiscount { get; set; }
    
        public virtual GoodsIssue GoodsIssue { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
