//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class UserReportControl
    {
        public int ReportControlID { get; set; }
        public int ReportID { get; set; }
        public string ReportGroupName { get; set; }
        public string ReportName { get; set; }
        public bool Enabled { get; set; }
    }
}
