//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class UserTree
    {
        public Nullable<int> id { get; set; }
        public int PrimaryID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> hasChildren { get; set; }
    }
}
